# -*- coding: utf-8 -*-
"""TEU Growth Rates.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CnajdPrJTFhtIywB8QfcMmG7H_kOu_iR
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from google.colab import files



uploaded = files.upload()
filename = list(uploaded.keys())[0]
df = pd.read_excel(filename)
df.head()

df.info()

df.shape

median_2020 = df['TEU 2020 (M)'].median()
print("Median of column 2020 TEU:", median_2020)

median_2021 = df['TEU 2021 (M)'].median()
print("Median of column 2021 TEU:", median_2021)

median_2022 = df['TEU 2022 (M)'].median()
print("Median of column 2022 TEU:", median_2022)

median_2023 = df['TEU 2023 (M)'].median()
print("Median of column 2023 TEU:", median_2023)

sns.kdeplot(df['TEU 2020 (M)'], fill=True)

plt.title(f'Kernel Density Estimate for TEU 2020 (M)')
plt.xlabel('TEU 2020 (M)')
plt.ylabel('Density')
plt.show()

sns.kdeplot(df['TEU 2021 (M)'], fill=True)


plt.title(f'Kernel Density Estimate for TEU 2021 (M)')
plt.xlabel('TEU 2021 (M)')
plt.ylabel('Density')
plt.show()

columns_to_plot = ['TEU 2021 (M)', 'TEU 2022 (M)', 'TEU 2023 (M)', 'TEU 2024 (M) (est)']

plt.figure(figsize=(10, 6))
for column in columns_to_plot:
    sns.kdeplot(df[column], fill=True, label=column)

plt.title('Kernel Density Estimate for TEU over the Years')
plt.xlabel('TEU')
plt.ylabel('Density')
plt.legend(title='Year')
plt.grid(True)

plt.show()

homevalue = df['Median Home Value (USD)'].median()
print("Median of column Home Value:", homevalue)

wage = df['Monthly Local Wage (USD)'].median()
print("Median of column Monthly Local Wage (USD):", wage)

homevalue = df['Median Home Value (USD)'].skew()
print("Skew of HOme value:", homevalue)

wage = df['Monthly Local Wage (USD)'].skew()
print("Skew of Local Wage (USD):", wage)

numeric_columns = ['TEU 2021 (M)', 'TEU 2022 (M)', 'TEU 2023 (M)', 'TEU 2024 (M) (est)','Monthly Local Wage (USD)','Median Home Value (USD)']  # Adjust as needed
correlation_matrix = df[numeric_columns].corr()

plt.figure(figsize=(10, 6))
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm", fmt=".2f", linewidths=0.5)

plt.title("Correlation Matrix (Selected Numeric Columns)")
plt.show()

df['Growth_21_20'] = ((df['TEU 2021 (M)'] - df['TEU 2020 (M)']) / df['TEU 2020 (M)']) * 100
df['Growth_22_21'] = ((df['TEU 2022 (M)'] - df['TEU 2021 (M)']) / df['TEU 2021 (M)']) * 100
df['Growth_23_22'] = ((df['TEU 2023 (M)'] - df['TEU 2022 (M)']) / df['TEU 2022 (M)']) * 100
df['Growth_24_22'] = ((df['TEU 2024 (M) (est)'] - df['TEU 2023 (M)']) / df['TEU 2023 (M)']) * 100

df.head(10)

df['TEU_CAGR_2020_2024 (%)'] = ((df['TEU 2024 (M) (est)'] / df['TEU 2020 (M)']) ** (1/4) - 1) * 100

df